[[entries."src/Config.php".issues]]
code = "cyclomatic-complexity"
start_line = 10
end_line = 181

[[entries."src/Config.php".issues]]
code = "no-boolean-flag-parameter"
start_line = 126
end_line = 126

[[entries."src/Config.php".issues]]
code = "no-else-clause"
start_line = 171
end_line = 178

[[entries."src/YamlParser.php".issues]]
code = "cyclomatic-complexity"
start_line = 13
end_line = 129

[[entries."src/YamlParser.php".issues]]
code = "no-else-clause"
start_line = 83
end_line = 90

[[entries."src/YamlParser.php".issues]]
code = "no-else-clause"
start_line = 104
end_line = 111

[[entries."src/YamlParser.php".issues]]
code = "prefer-early-continue"
start_line = 86
end_line = 88

[[entries."tests/src/ConfigTest.php".issues]]
code = "prefer-early-continue"
start_line = 86
end_line = 88

[[entries."tests/src/ConfigTest.php".issues]]
code = "too-many-methods"
start_line = 19
end_line = 296
